<?php

namespace Database\Seeders;

use App\Models\Symptom;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SymptomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $symptoms = array(
            "aarskog syndrome",
            "abdominal aortic aneurysm",
            "abdominal distension",
            "abdominal hernia",
            "abdominal pain",
            "abducens nerve palsy",
            "abetalipoproteinemia",
            "ablepharon macrostomia syndrome",
            "abnormal sweating",
            "abnormal vaginal bleeding",
            "abruptio placentae",
            "absence seizure",
            "acanthamoeba infection",
            "acanthamoeba keratitis",
            "acanthocytosis",
            "acanthosis nigricans",
            "accessory navicular bone",
            "achalasia",
            "achondroplasia",
            "acid reflux",
            "acne",
            "acoustic neuroma",
            "acquired brain injury",
            "acquired immunodeficiency syndrome (aids)",
            "acrocyanosis",
            "acromegaly",
            "actinic keratosis",
            "acute lymphoblastic leukaemia",
            "acute lymphoblastic leukemia (all)",
            "acute myeloid leukaemia",
            "acute myeloid leukemia (aml)",
            "addison's disease",
            "adenoidectomy",
            "adenoiditis",
            "adhesive capsulitis",
            "adie syndrome",
            "adie's pupil",
            "adrenal cancer",
            "adrenal gland tumours",
            "adrenocortical carcinoma",
            "adult still's disease",
            "agitation",
            "agoraphobia",
            "aicardi syndrome",
            "aids",
            "albinism",
            "alcohol misuse",
            "alcohol use disorder",
            "alcoholic liver disease",
            "alexander disease",
            "alkaptonuria",
            "allergic conjunctivitis",
            "allergic rhinitis",
            "allergies",
            "alopecia areata",
            "alpha-1 antitrypsin deficiency",
            "alport syndrome",
            "als",
            "alström syndrome",
            "altered sense of smell",
            "altered sense of taste",
            "alternating hemiplegia",
            "altitude sickness",
            "alzheimer's disease",
            "amblyopia",
            "amelogenesis imperfecta",
            "american trypanosomiasis (chagas disease)",
            "amnesia",
            "amniocentesis",
            "amyloidosis",
            "amyotrophic lateral sclerosis (als)",
            "anaemia",
            "anal cancer",
            "anal fissure",
            "anaphylaxis",
            "anaplastic astrocytoma",
            "androgen insensitivity syndrome",
            "anemia",
            "anencephaly",
            "aneurysm",
            "angelman syndrome",
            "angina pectoris",
            "angina",
            "angioedema",
            "anisocoria",
            "ankylosing spondylitis",
            "anorexia nervosa",
            "anterior cruciate ligament (acl) injury",
            "antiphospholipid syndrome",
            "anxiety disorders",
            "anxiety",
            "aortic aneurysm",
            "aortic stenosis",
            "aortic valve stenosis",
            "apert syndrome",
            "aphasia",
            "aphonia",
            "aplastic anaemia",
            "aplastic anemia",
            "appendicitis",
            "appetite loss",
            "apraxia",
            "arachnodactyly",
            "arachnoid cyst",
            "arachnoid cysts",
            "argininosuccinic aciduria",
            "argyll robertson pupil",
            "arm pain",
            "arnold-chiari malformation",
            "arrhythmia",
            "arrhythmogenic right ventricular dysplasia (arvd)",
            "arterial thrombosis",
            "arteriosclerosis",
            "arteriovenous malformation (avm)",
            "arthritis",
            "asbestosis",
            "ascariasis",
            "asperger syndrome",
            "aspergillosis",
            "asthma",
            "astigmatism",
            "astrocytoma",
            "ataxia telangiectasia",
            "ataxia",
            "atherosclerosis",
            "athetosis",
            "athlete's foot",
            "atopic dermatitis",
            "atrial fibrillation",
            "atrial flutter",
            "attention deficit hyperactivity disorder (adhd)",
            "autism spectrum disorder (asd)",
            "autism",
            "autoimmune diseases",
            "autoimmune hepatitis",
            "autoimmune pancreatitis",
            "autoimmune polyendocrine syndrome",
            "autoimmune progesterone dermatitis",
            "autonomic neuropathy",
            "avascular necrosis",
            "avian influenza",
            "avoidant personality disorder",
            "axillary nerve injury",
            "azotemia",
            "babesiosis",
            "babinski sign",
            "bacillary angiomatosis",
            "back pain",
            "bacterial endocarditis",
            "bacterial meningitis",
            "bad breath",
            "balance problems",
            "balanitis xerotica obliterans",
            "balanitis",
            "baldness",
            "barrett's esophagus",
            "bartter syndrome",
            "basal cell carcinoma",
            "becker muscular dystrophy",
            "bedwetting",
            "behcet's disease",
            "belching",
            "bell's palsy",
            "benign essential tremor",
            "benign fasciculation syndrome",
            "benign paroxysmal positional vertigo (bppv)",
            "benign prostatic hyperplasia (bph)",
            "beriberi",
            "beta thalassemia",
            "biliary atresia",
            "binge eating disorder",
            "bipolar disorder",
            "bird flu",
            "birth defects",
            "black eye",
            "black hairy tongue",
            "black lung disease",
            "black, tarry stool",
            "blackheads",
            "bladder cancer",
            "bladder problems",
            "blastomycosis",
            "bleeding gums",
            "bleeding in the brain",
            "bleeding in the lungs",
            "bleeding in the stomach",
            "blepharitis",
            "blepharospasm",
            "bloating",
            "blood clots",
            "blood disorders, such as low platelet counts or anemia",
            "blood in stool",
            "blood in urine",
            "bloody nose",
            "bloody stool",
            "bluish lips or face",
            "blurred vision",
            "body aches",
            "body odor",
            "bone cancer",
            "bone fractures",
            "bone pain",
            "borderline personality disorder (bpd)",
            "borderline personality disorder",
            "botulism",
            "brachial plexus injury",
            "brain aneurysm",
            "brain cancer",
            "brain injury",
            "brain tumor",
            "breast cancer",
            "breast lump",
            "breast pain",
            "breathing difficulties",
            "brittle nails",
            "bronchiectasis",
            "bronchitis",
            "brucellosis",
            "brugada syndrome",
            "bruising",
            "bubonic plague",
            "budd-chiari syndrome",
            "buerger's disease",
            "bulimia nervosa",
            "bullous pemphigoid",
            "burkitt lymphoma",
            "burkitt's lymphoma",
            "burning sensation",
            "burns",
            "bursitis",
            "caffeine use disorder",
            "calciphylaxis",
            "campylobacter infection",
            "cancer",
            "candidiasis",
            "canker sores",
            "capgras syndrome",
            "carbon monoxide poisoning",
            "carcinoid syndrome",
            "cardiac tamponade",
            "cardiomyopathy",
            "carotid artery disease",
            "carpal tunnel syndrome",
            "cat scratch fever",
            "cataplexy",
            "cataracts",
            "celiac disease",
            "central pontine myelinolysis",
            "cerebral aneurysm",
            "cerebral palsy",
            "cervical cancer",
            "cervical dystonia",
            "chagas disease",
            "chancroid",
            "charcot-marie-tooth disease",
            "chest congestion",
            "chest pain or discomfort",
            "chest pain",
            "chest tightness",
            "chickenpox",
            "chilblains",
            "childhood disintegrative disorder",
            "chills",
            "chlamydia",
            "cholangiocarcinoma",
            "cholecystitis",
            "cholera",
            "cholestasis",
            "chondrosarcoma",
            "chronic fatigue syndrome (cfs)",
            "chronic fatigue syndrome",
            "chronic fatigue",
            "chronic inflammatory demyelinating polyneuropathy (cidp)",
            "chronic inflammatory demyelinating polyneuropathy",
            "chronic kidney disease",
            "chronic lymphocytic leukemia (cll)",
            "chronic myeloid leukemia (cml)",
            "chronic obstructive pulmonary disease (copd)",
            "chronic pancreatitis",
            "chronic traumatic encephalopathy (cte)",
            "churg-strauss syndrome",
            "ciguatera fish poisoning",
            "cirrhosis",
            "cleft lip and cleft palate",
            "clonorchiasis",
            "clostridium difficile infection",
            "clubfoot",
            "cluster headaches",
            "cocaine addiction",
            "cocaine use disorder",
            "coccidioidomycosis",
            "cogan syndrome",
            "cold agglutinin disease",
            "cold hands and feet",
            "cold sores",
            "cold sweats",
            "colitis",
            "collagenous colitis",
            "colon cancer",
            "colon polyps",
            "color blindness",
            "coma",
            "common cold",
            "complex regional pain syndrome (crps)",
            "complex regional pain syndrome",
            "concussion",
            "confusion",
            "congenital adrenal hyperplasia",
            "congenital heart disease",
            "congestive heart failure",
            "conjunctivitis",
            "conn's syndrome",
            "constipation",
            "contact dermatitis",
            "conversion disorder",
            "corneal ulcer",
            "cornelia de lange syndrome",
            "coronary artery disease",
            "coronavirus disease 2019",
            "corticobasal degeneration",
            "costello syndrome",
            "cough",
            "coughing up blood",
            "coughing",
            "covid-19",
            "cowden syndrome",
            "cramping",
            "cramps",
            "craniosynostosis",
            "cravings",
            "creutzfeldt-jakob disease (cjd)",
            "crohn's disease",
            "croup",
            "cushing's syndrome",
            "cuts",
            "cyanosis",
            "cyclic vomiting syndrome",
            "cystic fibrosis",
            "cystitis",
            "cytomegalovirus (cmv) infection",
            "dandy-walker syndrome",
            "darier disease",
            "dark circles under eyes",
            "dark urine",
            "de quervain's tenosynovitis",
            "deafness",
            "decreased libido",
            "decreased motor function",
            "deep vein thrombosis (dvt)",
            "deep vein thrombosis",
            "deficiency anemia",
            "degenerative disc disease",
            "dehydration",
            "delayed ejaculation",
            "delayed sleep phase syndrome",
            "delirium",
            "delusions",
            "dementia",
            "dengue fever",
            "dependent personality disorder",
            "depersonalization disorder",
            "depression",
            "dermatitis herpetiformis",
            "dermatitis",
            "dermatomyositis",
            "desmoid tumor",
            "desmoid tumors",
            "developmental disabilities",
            "developmental dysplasia of the hip (ddh)",
            "diabetes insipidus",
            "diabetes mellitus",
            "diabetes",
            "diabetic ketoacidosis",
            "diabetic neuropathy",
            "diabetic retinopathy",
            "diarrhea",
            "difficulty breathing",
            "difficulty concentrating",
            "difficulty speaking",
            "difficulty swallowing",
            "diffuse idiopathic skeletal hyperostosis",
            "diffuse intrinsic pontine glioma (dipg)",
            "diffuse scleroderma",
            "digestive problems, such as cramping, constipation, diarrhea, and loss of appetite",
            "digitalis toxicity",
            "dilated cardiomyopathy",
            "diphtheria",
            "dislocated shoulder",
            "disorientation",
            "disseminated intravascular coagulation (dic)",
            "dissociative identity disorder",
            "diverticulitis",
            "diverticulosis",
            "dizziness",
            "double vision",
            "down syndrome",
            "dracunculiasis",
            "dressler syndrome",
            "dressler's syndrome",
            "drug abuse",
            "drug addiction",
            "dry eye syndrome",
            "dry mouth",
            "dry skin",
            "dubowitz syndrome",
            "dupuytren's contracture",
            "dysautonomia",
            "dysentery",
            "dyslexia",
            "dysmenorrhea",
            "dyspareunia",
            "dysphagia",
            "dyspraxia",
            "dysthymia",
            "dystonia",
            "dysuria",
            "e. coli infection",
            "eagle-barrett syndrome",
            "ear infection",
            "earache",
            "early-onset alzheimer's disease",
            "ebola virus disease",
            "ebola",
            "eccrine porocarcinoma",
            "echinococcosis",
            "eclampsia",
            "ectodermal dysplasia",
            "ectopic pregnancy",
            "eczema",
            "edema",
            "edwards syndrome",
            "ehlers-danlos syndrome",
            "ehlers-danlos syndromes",
            "ehrlichiosis",
            "eisenmenger syndrome",
            "electroconvulsive therapy (ect)",
            "elephantiasis",
            "elevated blood pressure",
            "ellis-van creveld syndrome",
            "embolism",
            "emphysema",
            "empty sella syndrome",
            "encephalitis lethargica",
            "encephalitis",
            "endocarditis",
            "endometrial cancer",
            "endometriosis",
            "enlarged lymph nodes",
            "enlarged prostate (bph)",
            "enteritis",
            "enterobiasis",
            "enterococcus infection",
            "enuresis",
            "eosinophilic esophagitis",
            "ependymoma",
            "epidermolysis bullosa",
            "epilepsy",
            "epiphora",
            "episodic ataxia",
            "epistaxis",
            "epstein-barr virus infection",
            "epstein-barr virus",
            "erectile dysfunction",
            "erysipelas",
            "erythema multiforme",
            "erythema",
            "erythromelalgia",
            "escherichia coli infection",
            "esophageal cancer",
            "esophageal reflux",
            "esophageal spasm",
            "essential tremor",
            "exanthem subitum",
            "exanthem",
            "excessive belching",
            "excessive gas",
            "excessive sweating",
            "excessive thirst",
            "exostoses",
            "extrahepatic bile duct cancer",
            "extreme hunger",
            "eye cancer",
            "eye discharge",
            "eye pain",
            "eyelid cancer",
            "fabry disease",
            "facial nerve problems",
            "facial paralysis",
            "facial swelling",
            "factor v leiden",
            "fahr's syndrome",
            "failure to thrive",
            "fainting or sudden loss of consciousness",
            "fainting",
            "familial adenomatous polyposis",
            "familial hypercholesterolemia",
            "familial mediterranean fever",
            "fanconi anemia",
            "farber disease",
            "farsightedness",
            "fasciitis",
            "fatigue",
            "febrile seizures",
            "fecal incontinence",
            "feeling cold",
            "feeling full after eating small amounts",
            "feeling hot",
            "feeling weak",
            "felty syndrome",
            "female infertility",
            "fetal alcohol syndrome",
            "fetal distress",
            "fever",
            "fibroadenoma",
            "fibrocystic breast disease",
            "fibrodysplasia ossificans progressiva",
            "fibromuscular dysplasia",
            "fibromyalgia",
            "fibrosarcoma",
            "fifth disease",
            "filariasis",
            "fistula",
            "flat feet",
            "flatulence",
            "flu",
            "flu-like symptoms",
            "flushing",
            "focal segmental glomerulosclerosis",
            "food allergies",
            "food allergy",
            "food poisoning",
            "foot pain",
            "foot ulcers",
            "foot-and-mouth disease",
            "foreign body in the eye",
            "forgetfulness",
            "fractures",
            "fragile x syndrome",
            "frequent and recurrent pneumonia, bronchitis, sinus infections, or ear infections",
            "frequent infections",
            "frequent urination",
            "friedreich's ataxia",
            "frontotemporal dementia",
            "frostbite",
            "frozen shoulder",
            "fungal infection",
            "fungal nail infections",
            "fungal skin infections",
            "furuncle",
            "furunculosis",
            "fused toes",
            "fussy baby",
            "galactorrhoea",
            "galactosaemia",
            "galactosemia",
            "gallbladder cancer",
            "gallstones",
            "gambling addiction",
            "ganglion cyst",
            "gangrene",
            "gardner syndrome",
            "gardner's syndrome",
            "gas gangrene",
            "gas",
            "gastric cancer",
            "gastric pain",
            "gastric ulcer",
            "gastrinoma",
            "gastritis",
            "gastroenteritis",
            "gastroesophageal reflux disease (gerd)",
            "gastrointestinal bleeding",
            "gastrointestinal perforation",
            "gastrointestinal stromal tumor (gist)",
            "gastrointestinal stromal tumour (gist)",
            "gastroparesis",
            "gaucher disease",
            "gaucher's disease",
            "generalised anxiety disorder (gad)",
            "generalized weakness",
            "genital herpes",
            "genital itching",
            "genital warts",
            "german measles",
            "gestational diabetes",
            "giant cell arteritis",
            "giardiasis",
            "gilbert syndrome",
            "gilbert's syndrome",
            "gingivitis",
            "glaucoma",
            "glioblastoma",
            "glioma",
            "glomerulonephritis",
            "glossitis",
            "glue ear",
            "gluten sensitivity",
            "goiter",
            "goitre",
            "gonorrhea",
            "gonorrhoea",
            "goodpasture syndrome",
            "goodpasture's syndrome",
            "gout",
            "graves' disease",
            "gray hair",
            "groin strain",
            "growths and lumps",
            "guillain-barre syndrome",
            "gum disease",
            "gynaecomastia",
            "haemangioma",
            "haemochromatosis",
            "haemolytic anaemia",
            "haemophilia",
            "haemophilus influenzae type b (hib) vaccine",
            "haemophilus influenzae type b (hib)",
            "hair dye reactions",
            "hair loss",
            "halitosis",
            "hallermann-streiff syndrome",
            "hallucinations",
            "hallux valgus",
            "hammer toe",
            "hand tremors",
            "hand, foot, and mouth disease",
            "hangover",
            "hantavirus pulmonary syndrome",
            "hashimoto's thyroiditis",
            "hay fever treatments",
            "hay fever",
            "head and neck cancer",
            "head injury",
            "head injury: first aid",
            "head lice and nits",
            "head lice",
            "headache",
            "headaches - tension-type",
            "headaches",
            "health anxiety",
            "healthy eating",
            "healthy weight",
            "hearing aids",
            "hearing loss",
            "heart attack - treatment",
            "heart attack - what to do",
            "heart attack",
            "heart block - treatment",
            "heart block",
            "heart disease",
            "heart failure - home monitoring",
            "heart failure - treatment",
            "heart failure",
            "heart murmurs - children",
            "heart murmurs",
            "heart palpitations - causes",
            "heart palpitations - treatment",
            "heart palpitations",
            "heart transplant",
            "heart valve disease",
            "heartburn",
            "heat exhaustion and heatstroke",
            "heat exhaustion",
            "heat rash",
            "heat stroke",
            "heatstroke",
            "heavy periods - treatment",
            "heavy periods",
            "helicobacter pylori (h. pylori) - treatment",
            "helicobacter pylori (h. pylori)",
            "hemangioma",
            "hematuria",
            "hemifacial spasm",
            "hemochromatosis",
            "hemolytic anemia",
            "hemophilia",
            "hemoptysis",
            "hemorrhoids",
            "henoch-schonlein purpura", 
            "hepatitis a - prevention",
            "hepatitis a - treatment",
            "hepatitis a",
            "hepatitis b - prevention",
            "hepatitis b - treatment",
            "hepatitis b",
            "hepatitis c - prevention",
            "hepatitis c - treatment",
            "hepatitis c",
            "hepatitis d",
            "hepatitis e",
            "hepatitis",
            "hepatocellular carcinoma",
            "hereditary hemorrhagic telangiectasia",
            "hernia - hiatus",
            "hernia - inguinal",
            "hernia - umbilical",
            "hernia",
            "herpes simplex eye infections",
            "herpes simplex virus",
            "herpes simplex",
            "herpes zoster (shingles)",
            "herpes",
            "hiatus hernia",
            "hiccups - causes",
            "hiccups",
            "hidradenitis suppurativa",
            "high blood pressure (hypertension) - treatment",
            "high blood pressure (hypertension)",
            "high blood pressure",
            "high cholesterol - prevention",
            "high cholesterol - treatment",
            "high cholesterol",
            "high fever",
            "hip arthroscopy",
            "hip dysplasia",
            "hip replacement",
            "hirschsprung disease",
            "hirsutism - treatment",
            "hirsutism",
            "histoplasmosis",
            "hiv and aids - living with hiv",
            "hiv and aids - post-exposure prophylaxis (pep)",
            "hiv and aids - reducing the risk",
            "hiv and aids - treatment",
            "hiv and aids",
            "hiv/aids",
            "hives - causes",
            "hives - treatment",
            "hives",
            "hoarding disorder",
            "hoarseness - causes",
            "hoarseness - treatment",
            "hoarseness",
            "hodgkin lymphoma - treatment",
            "hodgkin lymphoma",
            "homeopathy - evidence",
            "homeopathy - regulation",
            "homeopathy",
            "hormone replacement therapy (hrt) - alternatives",
            "hormone replacement therapy (hrt) - benefits and risks",
            "hormone replacement therapy (hrt) - side effects",
            "hormone replacement therapy (hrt)", 
            "hormone-secreting tumours",
            "horner syndrome",
            "hot flashes",
            "hpv infection",
            "hughes syndrome",
            "human granulocytic anaplasmosis (hga)",
            "human papillomavirus (hpv)",
            "huntington's disease - genetic testing",
            "huntington's disease",
            "hydrocephalus - treatment",
            "hydrocephalus",
            "hydronephrosis - treatment",
            "hydronephrosis",
            "hyperactivity",
            "hypercalcemia",
            "hypereosinophilic syndrome",
            "hyperglycaemia (high blood sugar) - causes",
            "hyperglycaemia (high blood sugar)",
            "hyperglycemia",
            "hyperhidrosis (excessive sweating) - treatment",
            "hyperhidrosis (excessive sweating)",
            "hyperhidrosis",
            "hyperparathyroidism - treatment",
            "hyperparathyroidism",
            "hyperpigmentation",
            "hyperprolactinemia",
            "hypersomnia",
            "hypertension",
            "hyperthyroidism - causes",
            "hyperthyroidism - treatment",
            "hyperthyroidism",
            "hypertrophic cardiomyopathy - treatment",
            "hypertrophic cardiomyopathy",
            "hyperventilation - causes",
            "hyperventilation - treatment",
            "hyperventilation",
            "hypoglycaemia (low blood sugar) - causes",
            "hypoglycaemia (low blood sugar) - treatment",
            "hypoglycaemia (low blood sugar)",
            "hypoglycemia",
            "hypohidrosis",
            "hypoparathyroidism - treatment",
            "hypoparathyroidism",
            "hypophosphatasia",
            "hypopituitarism",
            "hypothermia",
            "hypothyroidism - causes",
            "hypothyroidism - treatment",
            "hypothyroidism",
            "hysterectomy - alternatives",
            "hysterectomy - recovery",
            "hysterectomy - risks",
            "hysterectomy",
            "hysteroscopy - diagnostic",
            "hysteroscopy - operative",
            "hysteroscopy",
            "ibuprofen - side effects",
            "ibuprofen",
            "ichthyosis vulgaris - treatment",
            "ichthyosis vulgaris",
            "ichthyosis",
            "idiopathic intracranial hypertension",
            "idiopathic pulmonary fibrosis - living with",
            "idiopathic pulmonary fibrosis - treatment",
            "idiopathic pulmonary fibrosis",
            "idiopathic thrombocytopenic purpura (itp)",
            "ileitis",
            "iliotibial band syndrome",
            "immunisations - bcg",
            "immunisations - diphtheria, tetanus, pertussis (whooping cough) and polio",
            "immunisations - hepatitis a",
            "immunisations - hepatitis b",
            "immunisations - hib vaccine",
            "immunisations - hpv vaccine",
            "immunisations - menacwy vaccine",
            "immunisations - menb vaccine",
            "immunisations - pneumococcal vaccine",
            "immunisations - rotavirus vaccine",
            "immunisations - the flu vaccine",
            "immunisations",
            "impacted wisdom teeth - complications",
            "impacted wisdom teeth - removal",
            "impacted wisdom teeth",
            "impaired judgment",
            "impaired vision",
            "impetigo",
            "implants - dental",
            "implants",
            "impotence",
            "inability to concentrate",
            "inability to perform daily tasks",
            "inclusion body myositis",
            "incontinence - products",
            "incontinence - treatment",
            "incontinence",
            "increased appetite",
            "increased thirst",
            "increased urination",
            "indigestion - causes",
            "indigestion - treatment",
            "indigestion",
            "infant colic - treatment",
            "infant colic",
            "infantile spasms",
            "infection",
            "infertility - female",
            "infertility - male",
            "infertility",
            "inflammation and swelling of internal organs",
            "inflammation",
            "inflammatory bowel disease (ibd) - living with",
            "inflammatory bowel disease (ibd) - treatment",
            "inflammatory bowel disease (ibd)",
            "inflammatory bowel disease",
            "influenza (seasonal) - causes",
            "influenza (seasonal) - treatment",
            "influenza (seasonal)",
            "influenza (swine flu) - causes",
            "influenza (swine flu) - treatment",
            "influenza (swine flu)",
            "influenza",
            "ingrown toenail - prevention",
            "ingrown toenail - treatment",
            "ingrown toenail",
            "inherited heart conditions - diagnosis",
            "inherited heart conditions - genetic testing",
            "inherited heart conditions",
            "injury",
            "insect bites and stings - first aid",
            "insect bites and stings",
            "insomnia - causes",
            "insomnia - treatment",
            "insomnia",
            "insulin - side effects",
            "insulin",
            "intellectual disability - causes",
            "intellectual disability - support",
            "intellectual disability",
            "intermittent explosive disorder",
            "intersex - support",
            "intersex",
            "interstitial cystitis - treatment",
            "interstitial cystitis",
            "intestinal obstruction - treatment",
            "intestinal obstruction",
            "intrauterine growth restriction (iugr)",
            "iron deficiency anaemia - causes",
            "iron deficiency anaemia - treatment",
            "iron deficiency anaemia",
            "iron-deficiency anemia",
            "irregular heartbeat",
            "irregular periods - causes",
            "irregular periods - treatment",
            "irregular periods",
            "irritability",
            "irritable bowel syndrome (ibs) - causes",
            "irritable bowel syndrome (ibs) - treatment",
            "irritable bowel syndrome (ibs)",
            "irritable bowel syndrome",
            "ischaemic heart disease - causes",
            "ischaemic heart disease - treatment",
            "ischaemic heart disease",
            "ischemic colitis",
            "itching - causes",
            "itching - treatment",
            "itching",
            "itchy eyes",
            "itchy scalp",
            "itchy skin",
            "j wave syndrome",
            "j wave syndromes",
            "jaccoud arthropathy",
            "jackson-weiss syndrome",
            "jacksonian seizure",
            "jacobs syndrome",
            "jacobsen syndrome",
            "jalili syndrome",
            "jansen type metaphyseal chondrodysplasia",
            "jansen's metaphyseal chondrodysplasia",
            "japanese encephalitis",
            "japanese spotted fever",
            "jarcho-levin syndrome",
            "jaundice - causes",
            "jaundice - treatment",
            "jaundice",
            "jaw claudication",
            "jaw pain",
            "jaw tumors",
            "jellyfish stings",
            "jervell and lange-nielsen syndrome 1",
            "jervell and lange-nielsen syndrome 2",
            "jervell and lange-nielsen syndrome 3",
            "jervell and lange-nielsen syndrome 4",
            "jervell and lange-nielsen syndrome 5",
            "jervell and lange-nielsen syndrome 6",
            "jervell and lange-nielsen syndrome 7",
            "jervell and lange-nielsen syndrome",
            "jervell and lange-nielsen",
            "jervell-lange-nielsen syndrome",
            "jet lag - prevention",
            "jet lag - treatment",
            "jet lag",
            "job syndrome",
            "job's syndrome",
            "job-buckley syndrome",
            "jock itch",
            "johanson-blizzard syndrome",
            "johnson syndrome",
            "johnson-mcmillin syndrome",
            "johnson-mcmillin-treacher collins syndrome",
            "joint contracture",
            "joint dislocation",
            "joint effusion",
            "joint hypermobility syndrome",
            "joint pain - causes",
            "joint pain - treatment",
            "joint pain and stiffness",
            "joint pain",
            "joint stiffness",
            "joint swelling",
            "jones fracture of foot",
            "jones fracture",
            "jones syndrome",
            "joubert syndrome with congenital hepatic fibrosis",
            "joubert syndrome with hepatic defect",
            "joubert syndrome with ocular anomalies",
            "joubert syndrome with oculorenal anomalies",
            "joubert syndrome with renal agenesis",
            "joubert syndrome with renal cysts",
            "joubert syndrome with renal defect",
            "joubert syndrome with retinal dystrophy",
            "joubert syndrome",
            "jugular foramen syndrome",
            "jumping frenchmen of maine disorder",
            "junctional bradycardia",
            "junctional ectopic tachycardia",
            "junctional epidermolysis bullosa inversa",
            "junctional epidermolysis bullosa non-herlitz type",
            "junctional epidermolysis bullosa with pyloric atresia",
            "junctional epidermolysis bullosa",
            "junctional epidermolysis bullosa, generalized intermediate",
            "junctional epidermolysis bullosa, generalized severe",
            "junctional epidermolysis bullosa, herlitz type",
            "junctional nevus",
            "junctional rhythm",
            "junctional tachycardia",
            "juvenile amyotrophic lateral sclerosis",
            "juvenile angiofibroma",
            "juvenile arthritis",
            "juvenile dermatomyositis",
            "juvenile huntington disease",
            "juvenile hyaline fibromatosis",
            "juvenile idiopathic arthritis (jia) - living with",
            "juvenile idiopathic arthritis (jia) - treatment",
            "juvenile idiopathic arthritis (jia)",
            "juvenile idiopathic arthritis",
            "juvenile myasthenia gravis",
            "juvenile myelomonocytic leukemia",
            "juvenile myoclonic epilepsy",
            "juvenile nasopharyngeal angiofibroma",
            "juvenile onset diabetes mellitus",
            "juvenile pilocytic astrocytoma",
            "juvenile polyposis syndrome",
            "juvenile retinoschisis",
            "juvenile rheumatoid arthritis",
            "juvenile temporal arteritis",
            "juvenile xanthogranuloma",
            "juxtacanalicular connective tissue",
            "juxtacortical chondrosarcoma",
            "juxtacortical osteosarcoma",
            "juxtaglomerular cell tumor",
            "kala-azar",
            "kallmann syndrome",
            "kaposi's sarcoma",
            "kartagener syndrome",
            "kawasaki disease",
            "kearns-sayre syndrome",
            "keloids",
            "kennedy disease",
            "keratitis",
            "keratoacanthoma",
            "keratoconus",
            "keratosis pilaris",
            "kernicterus",
            "kidney cancer",
            "kidney disease",
            "kidney failure",
            "kidney infection",
            "kidney pain",
            "kidney stones",
            "kienböck's disease",
            "kikuchi disease",
            "kimura disease",
            "king-kopetzky syndrome",
            "kleine-levin syndrome",
            "klinefelter syndrome",
            "klippel-feil syndrome",
            "klippel-trenaunay syndrome",
            "klippel-trenaunay-weber syndrome",
            "kluver-bucy syndrome", 
            "knee pain",
            "knee swelling",
            "kniest dysplasia",
            "knock knees",
            "knocked-out tooth",
            "kohler's disease",
            "korsakoff syndrome",
            "korsakoff's syndrome",
            "krabbe disease",
            "kugelberg-welander disease",
            "kuru",
            "kwashiorkor",
            "kyphosis",
            "labyrinthitis",
            "lack of appetite",
            "lack of coordination",
            "lack of energy",
            "lactose intolerance",
            "lambert-eaton myasthenic syndrome",
            "landau-kleffner syndrome",
            "langerhans cell histiocytosis",
            "laryngeal cancer",
            "laryngitis",
            "lassa fever",
            "latex allergy",
            "lead poisoning",
            "leber's hereditary optic neuropathy",
            "leg cramps",
            "leg pain",
            "legg-calvé-perthes disease",
            "legionnaires' disease",
            "leigh's disease",
            "leiomyoma",
            "leishmaniasis",
            "lennox-gastaut syndrome",
            "leprosy",
            "leptomeningeal carcinomatosis",
            "leptospirosis",
            "leriche syndrome",
            "lesch-nyhan syndrome",
            "lethargy",
            "leukemia cutis",
            "leukemia",
            "leukocytosis",
            "leukodystrophy",
            "lewy body dementia",
            "lichen planus",
            "lichen sclerosus",
            "liddle syndrome",
            "light sensitivity",
            "lightheadedness or sudden dizziness",
            "lightheadedness",
            "ligneous conjunctivitis",
            "limb-girdle muscular dystrophy",
            "linear iga disease",
            "lipedema",
            "lipid metabolism disorder",
            "lipodystrophy",
            "lipoid proteinosis",
            "lipoma",
            "lissencephaly syndrome",
            "lissencephaly",
            "listeria infection",
            "listeriosis",
            "little league elbow",
            "livedo reticularis",
            "liver cancer",
            "liver disease",
            "liver failure",
            "locked-in syndrome",
            "lockjaw",
            "long chain acyl-coa dehydrogenase deficiency",
            "long qt syndrome",
            "loose anagen syndrome",
            "loss of appetite",
            "loss of balance",
            "loss of consciousness",
            "loss of taste or smell",
            "lou gehrig's disease (als)",
            "lou gehrig's disease",
            "low back pain",
            "low blood pressure",
            "low libido",
            "low testosterone",
            "lower back pain",
            "ludwig's angina",
            "lumbar spinal stenosis",
            "lump or mass",
            "lung cancer",
            "lung disease",
            "lupus erythematosus",
            "lupus nephritis",
            "lupus",
            "lyme disease",
            "lymph node enlargement",
            "lymphangioleiomyomatosis",
            "lymphedema",
            "lymphocytic colitis",
            "lymphogranuloma venereum",
            "lymphoma",
            "lymphomatoid papulosis",
            "lynch syndrome",
            "lysosomal storage disease",
            "machado-joseph disease",
            "macular degeneration",
            "mad cow disease",
            "malaria",
            "male breast cancer",
            "male infertility",
            "malignant hypertension",
            "malignant hyperthermia",
            "malignant melanoma",
            "malignant mesothelioma",
            "malignant neoplasm",
            "malignant otitis externa",
            "malignant tumor",
            "mallory-weiss syndrome",
            "manic depression",
            "marfan syndrome",
            "marfan's syndrome",
            "mastitis",
            "mastocytosis",
            "mcardle disease",
            "measles",
            "mediastinitis",
            "mediterranean fever",
            "medulloblastoma",
            "megaloblastic anemia",
            "melanoma",
            "melkersson-rosenthal syndrome",
            "memory loss",
            "memory problems",
            "meniere's disease",
            "meningitis",
            "menopause",
            "menorrhagia",
            "menstrual cramps",
            "meralgia paresthetica",
            "mesenteric adenitis",
            "mesothelioma",
            "metabolic acidosis",
            "metabolic alkalosis",
            "metabolic encephalopathy",
            "metabolic syndrome",
            "microcephaly",
            "microscopic polyangiitis",
            "migraine",
            "miller fisher syndrome",
            "mitochondrial myopathy",
            "mitral regurgitation",
            "mitral stenosis",
            "mitral valve prolapse",
            "mixed connective tissue disease",
            "moebius syndrome",
            "molluscum contagiosum",
            "mononucleosis",
            "mood changes",
            "mood disorder",
            "mood disorders",
            "mood swings",
            "morquio syndrome",
            "morton's neuroma",
            "motion sickness",
            "motor neuron disease",
            "mouth cancer",
            "mouth sores",
            "mouth ulcers",
            "moyamoya disease",
            "mucopolysaccharidosis",
            "mucormycosis",
            "mucositis",
            "mucus in stool",
            "multiple myeloma",
            "multiple sclerosis (ms)",
            "multiple sclerosis",
            "multiple system atrophy",
            "mumps",
            "munchausen syndrome by proxy",
            "munchausen syndrome",
            "muscle aches",
            "muscle cramps",
            "muscle spasms",
            "muscle strain",
            "muscle weakness",
            "muscular dystrophy",
            "myalgia",
            "myalgic encephalomyelitis",
            "myasthenia gravis",
            "mycoplasma pneumonia",
            "myelitis",
            "myelodysplastic syndrome (mds)",
            "myelodysplastic syndrome",
            "myelofibrosis",
            "myeloma",
            "myocardial infarction",
            "myocarditis",
            "myoclonic epilepsy",
            "myoclonus",
            "myofascial pain syndrome",
            "myopia",
            "myositis",
            "myxedema", 
            "nail abnormalities",
            "nail fungus",
            "narcolepsy",
            "nasal congestion",
            "nasal discharge",
            "nasal polyps",
            "nausea",
            "nausea, indigestion, heartburn, or abdominal pain",
            "neck pain",
            "neck stiffness",
            "necrosis",
            "necrotizing fasciitis",
            "neonatal jaundice",
            "neoplasm",
            "nephritis",
            "nephroblastoma",
            "nephrocalcinosis",
            "nephrogenic diabetes insipidus",
            "nephrogenic systemic fibrosis",
            "nephronophthisis",
            "nephropathy",
            "nephrosclerosis",
            "nephrotic syndrome",
            "nerve compression syndrome",
            "nerve pain",
            "nervousness",
            "neuralgia",
            "neuritis",
            "neurocysticercosis",
            "neuroendocrine tumor",
            "neurofibromatosis",
            "neurogenic bladder",
            "neuroleptic malignant syndrome",
            "neurosyphilis",
            "nicotine addiction",
            "niemann-pick disease",
            "night blindness",
            "night sweats",
            "nightmares",
            "nocardiosis",
            "nodding syndrome",
            "noise sensitivity",
            "non-hodgkin lymphoma",
            "non-hodgkin's lymphoma",
            "norovirus infection",
            "nosebleeds",
            "nosocomial infection",
            "numbness or tingling in the arms or legs",
            "numbness or tingling",
            "numbness",
            "nut allergy",
            "nystagmus",
            "obesity",
            "obsessive-compulsive disorder (ocd)",
            "obsessive-compulsive disorder",
            "obstructive sleep apnea",
            "occupational asthma",
            "ocd (obsessive-compulsive disorder)",
            "ocular herpes",
            "ohtahara syndrome",
            "oily skin",
            "opioid addiction",
            "opsoclonus-myoclonus syndrome",
            "optic neuritis",
            "oral cancer",
            "oral thrush",
            "organic brain syndrome",
            "ornithine transcarbamylase deficiency",
            "orthostatic hypotension",
            "osgood-schlatter disease",
            "osler-weber-rendu syndrome",
            "osteoarthritis",
            "osteogenesis imperfecta",
            "osteomalacia",
            "osteomyelitis",
            "osteoporosis",
            "otitis externa",
            "otitis media",
            "ovarian cancer",
            "ovarian cysts",
            "ovarian hyperstimulation syndrome",
            "ovarian torsion",
            "overactive bladder",
            "overheating",
            "oversensitivity to light",
            "overuse injuries",
            "overweight",
            "ovulation disorders",
            "oxalosis",
            "oxygen toxicity",
            "ozone depletion",
            "ozone layer",
            "ozone-oxygen cycle",
            "ozonide reactions",
            "ozonide",
            "ozonolysis of aldehydes",
            "ozonolysis of alkenes",
            "ozonolysis of alkynes",
            "ozonolysis of amides",
            "ozonolysis of amines",
            "ozonolysis of carboxylic acids",
            "ozonolysis of enol ethers",
            "ozonolysis of enols",
            "ozonolysis of ethers",
            "ozonolysis of halides",
            "ozonolysis of ketones",
            "ozonolysis of nitriles",
            "ozonolysis of nitro compounds",
            "ozonolysis of phenols",
            "ozonolysis of phosphines",
            "ozonolysis of silanes",
            "ozonolysis of sulfides",
            "ozonolysis of sulfones",
            "ozonolysis of terminal alkenes",
            "ozonolysis of thioethers",
            "ozonolysis of thiols",
            "ozonolysis of vinyl ethers",
            "ozonolysis of vinyl sulfides",
            "ozonolysis of ynamines",
            "ozonolysis of ynenes",
            "ozonolysis of α,β-unsaturated aldehydes",
            "ozonolysis of α,β-unsaturated amides",
            "ozonolysis of α,β-unsaturated amines",
            "ozonolysis of α,β-unsaturated azides",
            "ozonolysis of α,β-unsaturated carbonyl compounds",
            "ozonolysis of α,β-unsaturated carboxylic acids",
            "ozonolysis of α,β-unsaturated esters",
            "ozonolysis of α,β-unsaturated ethers",
            "ozonolysis of α,β-unsaturated halides",
            "ozonolysis of α,β-unsaturated imines",
            "ozonolysis of α,β-unsaturated isocyanates",
            "ozonolysis of α,β-unsaturated isothiocyanates",
            "ozonolysis of α,β-unsaturated ketimines",
            "ozonolysis of α,β-unsaturated ketones",
            "ozonolysis of α,β-unsaturated nitriles",
            "ozonolysis of α,β-unsaturated nitrilimines",
            "ozonolysis of α,β-unsaturated nitro compounds",
            "ozonolysis of α,β-unsaturated nitroso compounds",
            "ozonolysis of α,β-unsaturated oxaziridines",
            "ozonolysis of α,β-unsaturated oxazolines",
            "ozonolysis of α,β-unsaturated oximes",
            "ozonolysis of α,β-unsaturated phenols",
            "ozonolysis of α,β-unsaturated phosphines",
            "ozonolysis of α,β-unsaturated pyridines",
            "ozonolysis of α,β-unsaturated pyrimidines",
            "ozonolysis of α,β-unsaturated pyrroles",
            "ozonolysis of α,β-unsaturated quinolines",
            "ozonolysis of α,β-unsaturated silanes",
            "ozonolysis of α,β-unsaturated sulfides",
            "ozonolysis of α,β-unsaturated sulfonamides",
            "ozonolysis of α,β-unsaturated sulfones",
            "ozonolysis of α,β-unsaturated sulfonyl azides",
            "ozonolysis of α,β-unsaturated sulfonyl chlorides",
            "ozonolysis of α,β-unsaturated sulfonyl hydrazides",
            "ozonolysis of α,β-unsaturated sulfonyl imides",
            "ozonolysis of α,β-unsaturated sulfonyl isocyanates",
            "ozonolysis of α,β-unsaturated sulfonyl nitriles",
            "ozonolysis of α,β-unsaturated sulfonyl oximes",
            "ozonolysis of α,β-unsaturated sulfonyl thiocarbonyls",
            "ozonolysis of α,β-unsaturated sulfonyl thioesters",
            "ozonolysis of α,β-unsaturated sulfoxides",
            "ozonolysis of α,β-unsaturated sulfoximines",
            "ozonolysis of α,β-unsaturated thiazoles",
            "ozonolysis of α,β-unsaturated thioamides",
            "ozonolysis of α,β-unsaturated thiocarbonyls",
            "ozonolysis of α,β-unsaturated thioesters",
            "ozonolysis of α,β-unsaturated thioethers",
            "ozonolysis of α,β-unsaturated thiols",
            "ozonolysis of α,β-unsaturated thiones",
            "ozonolysis of α,β-unsaturated triazoles",
            "ozonolysis of α,β-unsaturated uracils",
            "ozonolysis of α,β-unsaturated xanthates",
            "ozonolysis of α,β-unsaturated ynamides",
            "ozonolysis of α,β-unsaturated ynamines",
            "ozonolysis of α,β-unsaturated ynenes",
            "ozonolysis",
            "pachyonychia congenita",
            "paget's disease of bone",
            "pain",
            "painful intercourse",
            "painful joints",
            "painful menstruation",
            "painful urination",
            "pale skin",
            "pallor",
            "palpitations",
            "pancreatic cancer",
            "pancreatitis",
            "panhypopituitarism",
            "panic attacks",
            "panic disorder",
            "paralysis",
            "paraneoplastic syndromes",
            "paranoia",
            "paresthesia",
            "parkinson's disease",
            "parry-romberg syndrome",
            "patau syndrome",
            "pelvic inflammatory disease (pid)",
            "pelvic pain",
            "pemphigus vulgaris",
            "pemphigus",
            "peptic ulcer disease",
            "peptic ulcer",
            "pericarditis",
            "periodic paralysis",
            "periodontal disease",
            "periodontitis",
            "peripheral artery disease",
            "peripheral neuropathy",
            "peritonitis",
            "personality changes",
            "personality disorders",
            "pertussis (whooping cough)",
            "phantom limb pain",
            "pharyngitis",
            "phenylketonuria",
            "phlebitis",
            "phlegm",
            "phobias",
            "photophobia",
            "pica",
            "pick's disease",
            "piles (hemorrhoids)",
            "pink eye (conjunctivitis)",
            "pink eye",
            "piriformis syndrome",
            "pituitary tumors",
            "plantar fasciitis",
            "pleurisy",
            "pms",
            "pneumonia",
            "poison ivy rash",
            "polio",
            "polycystic kidney disease (pkd)",
            "polycystic ovary syndrome (pcos)",
            "polycystic ovary syndrome",
            "polymicrogyria",
            "polymyalgia rheumatica",
            "polymyositis",
            "poor appetite",
            "poor balance",
            "poor concentration",
            "poor coordination",
            "poor memory",
            "porphyria",
            "post-traumatic stress disorder (ptsd)",
            "post-traumatic stress disorder",
            "postnasal drip",
            "postural orthostatic tachycardia syndrome",
            "prader-willi syndrome",
            "premature ejaculation",
            "premenstrual dysphoric disorder (pmdd)",
            "premenstrual syndrome",
            "primary biliary cirrhosis",
            "primary sclerosing cholangitis",
            "progeria",
            "progressive supranuclear palsy",
            "prostate cancer",
            "prostate problems",
            "prostatitis",
            "protein s deficiency",
            "proteinuria",
            "pseudotumor cerebri",
            "psoriasis",
            "psoriatic arthritis",
            "psychosis",
            "pubic lice",
            "puffy eyes",
            "pulmonary alveolar proteinosis",
            "pulmonary embolism",
            "pulmonary fibrosis",
            "pyelonephritis",
            "pyoderma gangrenosum",
            "pyometra",
            "pyomyositis",
            "pyrethrin poisoning",
            "pyromania",
            "q fever endocarditis",
            "q fever",
            "q fever, chronic",
            "qalb alasad",
            "qazi markouizos syndrome",
            "qazi-markouizos syndrome",
            "qingmen-jiangya decoction poisoning",
            "qishen yiqi dripping pill poisoning",
            "qjm",
            "qms",
            "qof",
            "qpax",
            "qrs complex",
            "qt interval prolongation",
            "qt syndrome",
            "quadratus lumborum syndrome",
            "quadriceps contusion",
            "quadriceps tendinitis",
            "quadriparesis",
            "quadriplegia",
            "quadruple screen",
            "quaking aspen",
            "qualitative research",
            "quality assurance",
            "quality control",
            "quantitative research",
            "quantum mechanics",
            "quarantine",
            "quartan malaria",
            "quaternary structure",
            "quebec platelet disorder",
            "queen anne's lace",
            "quercetin",
            "quetiapine",
            "quickening",
            "quinine",
            "quinism",
            "quinsy",
            "quintuplets",
            "quiver belly",
            "quivering tongue",
            "quivering voice",
            "qwerty syndrome",
            "rabies",
            "ramsay hunt syndrome",
            "rapid breathing",
            "rapid heartbeat",
            "rapid or fluttering heartbeats (palpitations)",
            "rash",
            "raynaud's disease",
            "raynaud's phenomenon",
            "reactive arthritis",
            "rectal bleeding",
            "red eyes",
            "redness",
            "reflex sympathetic dystrophy syndrome",
            "refractive errors",
            "reiter's syndrome",
            "renal cell carcinoma",
            "respiratory syncytial virus (rsv)",
            "restless legs syndrome",
            "restlessness",
            "retinitis pigmentosa",
            "retinoblastoma",
            "rett syndrome",
            "reye's syndrome",
            "rh incompatibility",
            "rheumatoid arthritis",
            "rickets",
            "riley-day syndrome",
            "ringworm",
            "rocky mountain spotted fever",
            "rosacea",
            "rotavirus",
            "roundworm",
            "rubella",
            "runny nose",
            "runny or stuffy nose",
            "ruptured spleen",
            "sadness",
            "salmonella infection",
            "sarcoidosis",
            "sars-cov-2",
            "scabies",
            "scaly skin",
            "scarlet fever",
            "scheuermann's disease",
            "schizoaffective disorder",
            "schizophrenia",
            "sciatica",
            "scleritis",
            "scleroderma",
            "scoliosis",
            "seasonal affective disorder (sad)",
            "seasonal affective disorder",
            "seborrheic dermatitis",
            "seizures",
            "sensitivity to cold",
            "sensitivity to heat",
            "sensitivity to light",
            "sepsis",
            "septicemia",
            "severe headache",
            "sexual dysfunction",
            "sexually transmitted diseases (stds)",
            "sexually transmitted infections (stis)",
            "shaking",
            "shallow breathing",
            "shigellosis",
            "shin splints",
            "shingles",
            "short-term memory loss",
            "shortness of breath",
            "shoulder pain",
            "sickle cell anemia",
            "sinus congestion",
            "sinus infection",
            "sinus pain",
            "sinusitis",
            "sjogren's syndrome",
            "sjogren-larsson syndrome",
            "skin discoloration",
            "skin growths",
            "skin irritation",
            "skin lesions",
            "skin nodules",
            "skin rash",
            "skin rashes and lesions",
            "skin redness",
            "skin thickening",
            "sleep apnea",
            "sleep disturbances",
            "sleepwalking",
            "slurred speech",
            "smallpox",
            "sneezing",
            "snoring",
            "sore eyes",
            "sore throat",
            "speech difficulties",
            "spina bifida",
            "spinal muscular atrophy",
            "sprains and strains",
            "staph infections",
            "stiff joints",
            "stiff neck",
            "stiff-person syndrome",
            "still's disease",
            "stomach cancer",
            "stomach cramps",
            "stomach flu",
            "stomach pain",
            "stomach ulcers",
            "strep throat",
            "stress and anxiety",
            "stroke",
            "stuffy nose",
            "sturge-weber syndrome",
            "subacute sclerosing panencephalitis",
            "substance abuse",
            "suicide",
            "sunburn",
            "sweating",
            "sweet's syndrome",
            "swelling in the legs, ankles, or feet",
            "swelling",
            "swine flu",
            "swollen glands",
            "swollen joints",
            "swollen lymph nodes",
            "sydenham chorea",
            "synovial chondromatosis",
            "syphilis",
            "systemic lupus erythematosus (sle)",
            "takayasu's arteritis",
            "tardive dyskinesia",
            "tarsal tunnel syndrome",
            "tay-sachs disease",
            "teeth grinding",
            "temporal arteritis",
            "tenderness",
            "tendinitis",
            "tennis elbow",
            "tension headaches",
            "tension",
            "testicular cancer",
            "testicular pain",
            "tetanus",
            "thalassemia",
            "thirst",
            "throat cancer",
            "throat clearing",
            "throat tightness",
            "thrombocytopenia",
            "thyroid cancer",
            "thyroid eye disease",
            "tietze syndrome",
            "tingling",
            "tinnitus",
            "tiredness",
            "toe numbness",
            "tongue swelling",
            "tonsillitis",
            "tooth decay",
            "toothache",
            "tourette syndrome",
            "toxic shock syndrome",
            "transverse myelitis",
            "trembling",
            "tremors",
            "trichomoniasis",
            "trigeminal neuralgia",
            "trouble concentrating",
            "trouble sleeping",
            "tuberculosis (tb)",
            "tuberculosis",
            "tuberous sclerosis",
            "tularemia",
            "turner syndrome",
            "type 1 diabetes",
            "type 2 diabetes",
            "ulcerative colitis",
            "ulcers",
            "uncontrollable movements",
            "unexplained bruising",
            "unexplained weight gain",
            "unexplained weight loss",
            "unsteady gait",
            "upper body pain or discomfort in the arms, back, neck, jaw, or upper stomach",
            "upset stomach",
            "urgent urination",
            "urinary incontinence",
            "urinary tract infection (uti)",
            "urinary tract infection",
            "urinary tract infections",
            "urticaria pigmentosa",
            "urticaria",
            "usher syndrome",
            "uterine cancer",
            "vaginal cancer",
            "vaginal discharge",
            "vaginal itching",
            "varicose veins",
            "vasculitis",
            "vertigo",
            "vestibular migraine",
            "viral gastroenteritis",
            "viral hepatitis",
            "vision changes",
            "vision loss",
            "vision problems",
            "visual disturbances",
            "vitamin deficiencies",
            "vocal hoarseness",
            "vomiting blood",
            "vomiting",
            "von hippel-lindau disease",
            "von willebrand disease",
            "waldenstrom macroglobulinemia",
            "weakness",
            "wegener's granulomatosis",
            "weight gain",
            "weight loss",
            "wermer syndrome",
            "west nile virus infection",
            "west nile virus",
            "wheezing",
            "whipple's disease",
            "whooping cough",
            "williams syndrome",
            "wilson's disease",
            "wiskott-aldrich syndrome",
            "worsening vision",
            "wrist pain",
            "x-linked adrenoleukodystrophy",
            "x-linked agammaglobulinemia",
            "x-linked hypophosphatemia",
            "xeroderma pigmentosum",
            "xeroderma",
            "xerostomia",
            "yakutia encephalitis",
            "yawning",
            "yaws",
            "yearning for sleep",
            "yeast infection",
            "yellow eyes",
            "yellow fever",
            "yellow skin or eyes",
            "yellow skin",
            "yellowing of the eyes",
            "yellowing of the skin and eyes",
            "yellowing of the skin",
            "yersinia enterocolitica infection",
            "yersiniosis",
            "zellweger syndrome",
            "zika virus infection",
            "zika virus",
            "zinc deficiency",
            "zits",
            "zollinger-ellison syndrome",
            "zoonosis",
            "zoonotic allergic infections",
            "zoonotic antimicrobial-resistant infections",
            "zoonotic autoimmune infections",
            "zoonotic bacterial infections",
            "zoonotic biohazard infections",
            "zoonotic biological warfare infections",
            "zoonotic bioterrorism infections",
            "zoonotic cardiovascular infections",
            "zoonotic covid-19",
            "zoonotic ear infections",
            "zoonotic emerging infections",
            "zoonotic endemic infections",
            "zoonotic endocrine infections",
            "zoonotic environmental infections",
            "zoonotic epidemic infections",
            "zoonotic eye infections",
            "zoonotic foodborne diseases",
            "zoonotic fungal infections",
            "zoonotic genetic infections",
            "zoonotic helminthic infections",
            "zoonotic hematological infections",
            "zoonotic hepatic infections",
            "zoonotic iatrogenic infections",
            "zoonotic idiopathic infections",
            "zoonotic immunological infections",
            "zoonotic influenza",
            "zoonotic lymphatic infections",
            "zoonotic metabolic infections",
            "zoonotic musculoskeletal infections",
            "zoonotic neglected infections",
            "zoonotic neurological infections",
            "zoonotic nutritional infections",
            "zoonotic occupational infections",
            "zoonotic oncological infections",
            "zoonotic oral infections",
            "zoonotic orphan infections",
            "zoonotic pandemic infections",
            "zoonotic parasitic infections",
            "zoonotic prion diseases",
            "zoonotic protozoal infections",
            "zoonotic psychiatric infections",
            "zoonotic rare infections",
            "zoonotic re-emerging infections",
            "zoonotic recreational infections",
            "zoonotic renal infections",
            "zoonotic respiratory infections",
            "zoonotic sexually transmitted infections",
            "zoonotic skin infections",
            "zoonotic travel-related infections",
            "zoonotic tuberculosis",
            "zoonotic vector-borne diseases",
            "zoonotic viral hemorrhagic fever",
            "zoonotic viral infections",
            "zoonotic waterborne diseases",
            "zoster",
            "zygomycosis",
        );

        foreach ($symptoms as $symptom) {
            Symptom::factory(1)->create([
                'name' => $symptom,
            ]);
            # code...
        }
    }
}