version: "3"
services:
    web:
        restart: always
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    php:
        build:
          context: .
          dockerfile: ./docker/Dockerfile
        restart: always
        environment: 
            DB_HOST: mysql
            DB_NAME: doctor-appointment-system
            DB_USER: root
            DB_PASS: root
            DB_PORT: 3306
        volumes:
            - ./:/var/www
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
            - ./docker/database:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8081:80"
        restart: always